/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ItemLendingSystem;

import org.junit.Test;

import ItemLendingSystem.Model.Member;

import static org.junit.Assert.*;

import org.junit.Assert;

public class AppTest {
   
    /* Check to see if the ID length is 6 */
    @Test public void checkIdLength() {
        Member m = new Member("Lukas", "Gunnarsson", "0707123123", "lukas@gmail.com");
        assert (m.getId().length() == 6);
    }
}
